version: "3.8"
services:
  db:
    build: ./db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    networks:
      - backend
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    restart: always
  web:
    build: ./web
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    networks:
      - backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure 
  networks:
    name: test_network
    # Use a custom driver which takes special options
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"
    front-tier:
      ipv4_address: 172.16.238.10
      ipv6_address: 2001:3984:3989::10