version: "3.8"
services:
  db:
    container_name: 'db'
    build: ./db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    networks:
      - backend
    volumes:
      - 'db:/var/lib/mysql'
    restart: always
  web:
    container_name: 'web'
    build: ./web
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - db
    restart: on-failure 
  
networks:
  backend:
    driver: bridge

volumes:
  db: